apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  namespace: xmrig
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: xmrig
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        env:
        - name: ADDRESS
          value: {{ .Values.env.walletAddress }}
        - name: WORKER_ID
          value: {{ .Values.env.worker }}

        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
