apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  namespace: xmrig
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: xmrig
        resources: {}
        env:
        - name: DEFAULT_PASSWORD
          value: {{ .Values.configs.defaultPassword }}
        - name: ADDRESS
          value: {{ .Values.configs.defaultPassword }}
        securityContext: {}
