image:
  name: gcr.io/its-artifact-commons/station-monitoring
  tag: latest

configs: {}
replica: 1

env:
  walletAddress: change-here
  worker: change-here
  sock5Address: 127.0.0.1:9050
  url: rx.unmineable.com:3333

resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "3Gi"
    cpu: "3"
